project_id = "pxdigcofmljlgwohscmb"

[functions.mark-email-responded]
verify_jwt = false

[functions.send-scheduled-emails]
verify_jwt = false

[functions.send-daily-summary]
verify_jwt = false

[functions.send-new-topic-notification]
verify_jwt = false

[functions.send-topic-closed-notification]
verify_jwt = false